"""added fild timestop

Revision ID: 64ef660064d6
Revises: 622f3d9f3136
Create Date: 2022-07-28 12:24:58.853322

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '64ef660064d6'
down_revision = '622f3d9f3136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('URL_map', sa.Column('timestop', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_URL_map_timestop'), 'URL_map', ['timestop'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_URL_map_timestop'), table_name='URL_map')
    op.drop_column('URL_map', 'timestop')
    # ### end Alembic commands ###
